site_name: Examen_Unidad_6

site_url: https://danielmarinhomartinez.github.io/Examen_Unidad_6/

# docs es donde se encuentran los archivos de entrada (archivos .md y .pdf)
docs_dir: 'docs'

# site es donde se generarán los archivos estáticos
site_dir: 'site'

theme:
  name: 'readthedocs'

# Configuración de la navegación
nav:
  
  - Guia Instalacion windows 11: Guía_de_Instalación_Windows_11.md
  - Guía del iphone 16: Especificaciones_Técnicas_iPhone_16.md
  





